### PR TITLE
Add support for [^] style footnotes

### PR DESCRIPTION
**Pull request by rustle**
First pass at supporting footnotes. Open to feedback.

High-level stuff:

* I added `ReadableFragment` to allow me to build up a `Fragment` not from `Reader` so I can build the `FootnoteList`. It's a little clunky, interested to hear if you have suggestions for a better approach that's not too disruptive to gathering up URL references.
* There's a note in `Link` where I read in the same `Substring` twice and am not sure if it should instead try to get that substring out of `FormattedText` (meaning new API).
* Converted `URLDeclaration` to `Reference` in an attempt to make it clear it was in the list of references usually at the end of the document that maybe a `URL` or a `Footnote`. Open to different naming if there's something clearer or some reason to stick with `URLDeclaration`. Just `Declaration` might be a good alternative.
* Not sure what's available for perf testing.
* There's only one very simple test, probably should have a few more.
* Currently haven't thought much about customizing the HTML produced for `Footnote`, `FootnoteList` and `Link.Target.footnote`.

Lemme know what you think.

### CODE REVIEW

**Comment by rustle** [comment]
Went ahead and switched `Reference` to `Declaration`

**Comment by rustle** [comment]
New implementation that's a bit more complete, should be easier to modify footnotes/footnotes list. A bit more invasive, would be glad to hear any notes.

**Comment by rustle** [comment]
Should I close this PR?

**Comment by JulianKahnert** [comment]
@rustle why are you closing this PR? It looks good and I really need this feature. @JohnSundell what do you think?

**Comment by rustle** [comment]
@JulianKahnert seemed like a dead end ¯\_(ツ)_/¯

**Pull request closed without merging**
