### PR TITLE
Removed Linux testing apparatus in favor of test discovery

### PR DESCRIPTION
**Pull request by john-mueller**
As of Swift 5.1, testing on Linux can now be accomplished by running `swift test --enable-test-discovery`. All the Linux testing aids can be removed from code, reducing complexity and the need to manually add test cases when changed. Verified that all tests are discovered and run as expected on Linux.

Tests/LinuxMain.swift is still required, or else `swift build` will fail, but it can be repurposed to display instructions on how to run the tests.

⚠️ This is expected to fail the Linux CI test until the bitrise.yml file for Linux testing is modified to include `--enable-test-discovery`.

### CODE REVIEW

**Comment by john-mueller** [comment]
If you change the bitrise.yml config, I'll push a minor tweak to rerun the CI tests.

**Comment by JohnSundell** [comment]
I think it's too early to enable this. I'd like to wait until Linux test discovery is on by default.

**Comment by john-mueller** [comment]
Feel free to close this PR, or leave it open until things stabilize.

**Comment by JohnSundell** [comment]
I'll close it for now. Thanks anyway @john-mueller 🙂

**Pull request closed without merging**
