### PR TITLE
Make Reader public

### PR DESCRIPTION
**Pull request by adam-fowler**
You provide us with a method to modify how html is generated from markdown with the `MarkdownParser.addModifier` function. But then you don't provide us with any of the tools you have written to parse the markdown. I could re-implement the Reader class in my own code but seems it would be more sensible to use what is already there.

### CODE REVIEW

**Comment by JohnSundell** [comment]
Modifiers aren't meant to re-parse the Markdown - why would they, it's already parsed? Could you please provide an example use case of when you'd require direct access to the `Reader` type? I'm afraid that making it public would involve a bit more work than just adding the `public` modifier to it.

**Comment by adam-fowler** [comment]
The example I've got I'm actually parsing the resultant HTML.
I want to prefix a CDN address to all the image URLs.

**Comment by steve-h** [comment]
@adam-fowler I have the area where I think you need your change.
From an different PR
``` swift
 func html(usingURLs urls: NamedURLCollection,
              modifiers: ModifierCollection) -> String {
*** the modifiers should be called here before the encoding for security
        let url = uriEncoded(uriSubstring: target.url(from: urls))
        let title = text.html(usingURLs: urls, modifiers: modifiers)
        return "<a href=\"\(url)\">\(title)</a>"
    }
```

The modifiers are not called even if added to the parser.
You would then modify the parsed URL that starts with /image/... to be your CDN

**Comment by adam-fowler** [comment]
@steve-h are you suggesting a modifier that is applied to all URLs? In the situation above I described it would work. The other thought I had was generated `img` `srcset` attributes. Not sure how I get that without parsing the html generated.

**Comment by steve-h** [comment]
Well that opens up a big topic..
There is an open topic about adding attributes in markdown [https://talk.commonmark.org/t/consistent-attribute-syntax/272](https://talk.commonmark.org/t/consistent-attribute-syntax/272)

This is not in near future and I don't personally think that such a deployment decision should be in the Markdown source or its initial processing.

My thinking for modifying content source, whether generated with markdown or other html tooling is to actually add a Publish step to turn the html into a DOM tree using SwiftSoup for example.

Then SwiftSoup has JQuery like modification capabilities and you would manipulate all the image element in this AST form and the output the html from SwiftSoup to hand back to Publish.

I don't really think that mangling the DOM in markdown form makes any sense. Not that it could not be done; just that it is too clever a solution to a hard publishing problem.

**Comment by adam-fowler** [comment]
I'm not looking to add attributes in markdown. Just want to edit the generated HTML. Creating a DOM tree seems a little bit of overkill for what I want but obviously could be very useful.

**Comment by adam-fowler** [comment]
Closing this just implemented my own Reader class

**Pull request closed without merging**
