### PR TITLE
Adding id to Header Tag

### PR DESCRIPTION
**Pull request by fishcharlie**
This PR is still a work in progress. But submitting it for now just to gather feedback and ensure @JohnSundell and the rest of the community supports this change before pressing forward and dedicating a lot of time to it.

A lot of other markdown parsers set tags for headers so that it's easy to add hyperlinks to different parts of the page. The goal of this PR is to add that functionality to Ink.

I do have `Allow edits from maintainers.` checked, so any maintainers of this repo can push to my branch if you would like to contribute to this PR.

---

Todo Items:

- [ ] Add support for spaces and special characters in header (ensure they work correctly with id)
- [ ] Add/Update tests

### CODE REVIEW

**Comment by fishcharlie** [comment]
@JohnSundell Is this something you would be open to merging if I worked on finishing this pull request? Just don't want to put a lot of effort into it if you are opposed to it.

**Comment by JohnSundell** [comment]
No, I don't think so. I think this kind of functionality is much better implemented as modifiers, since different sites are likely to want to use different formats for their header IDs. I have such a modifier for my site for example, and I wouldn't want Ink to impose any such behavior on my templates.

**Comment by fishcharlie** [comment]
@JohnSundell Got it. For modifiers, is there any documentation for that? Just trying to figure out the best way to add this functionality to my site. So a point in the right direction would be very appreciated.

**Comment by JohnSundell** [comment]
All of the documentation that's currently available for Ink can be found within this repo. There's no external documentation site or anything like that. So your best bet is to check out [the API documentation for `Modifier`](https://github.com/JohnSundell/Ink/blob/master/Sources/Ink/API/Modifier.swift) to get started. There's also a [section in the README](https://github.com/JohnSundell/Ink#powerful-customization) that contains an example of using modifiers.

**Comment by fishcharlie** [comment]
@JohnSundell Perfect. I think that at least gets me started. Thank you so much!

**Pull request closed without merging**
